### ISSUE TITLE
Instead of showing an arrow, the plugin spams "Cannot reach destination from here" until the player finishes that quest stage.

### ISSUE THREAD

**Issue by nuttapillar** [PikaMug/GPS-Quests#10]
Sometimes, instead of pointing to a location, The gps-quests spams "Cannot reach destination from here" until the player manually tracks down the objective. This message seems to happen when the objective is to speak to an npc who moves around.

![image](https://user-images.githubusercontent.com/22978620/180450005-498ccad3-1a85-40d3-82fa-209d04f8609e.png)

**Comment by PikaMug** [comment]
When you say an NPC who moves around, what mechanism are you using to move it?

**Comment by nuttapillar** [comment]
I use npcdestinations to move them

**Comment by PikaMug** [comment]
Pretty sure recent versions resolve this. If not, let me know.
