### ISSUE TITLE
Arrow stop at first location.

### ISSUE THREAD

**Issue by Prowco** [PikaMug/GPS-Quests#12]
Hi i update quests and gps quests to to the lastest version quests 4.8.2 and gps-quest 1.9 but now when i start the quest the arrow just show the first location when you reach the first location the arrow stop and now if you dont have the route to the next location there is no way to find it and in gps-quest 1.4 and quests 3.8.2 works with out problem could you help me please.

**Comment by PikaMug** [comment]
Please identify whether the issue is with GPS-Quests or Quests itself. Meaning, try updating one but not the other to deduce which is the problem.
