### ISSUE TITLE
GPS commands don't work in Events

### ISSUE THREAD

**Issue by ghost** [PikaMug/GPS-Quests#2]
I created command-event what start gps to certain point with command (compass start point player) when the player finish the quest. The gps started, the plugin write the gps start message, but no arrow and the gps is not active (see the picture).

If I run the same command as player, this work perfectly. 

Without the GPS-quest plugin (only with the GPS) this work fine.

![gps_problema](https://user-images.githubusercontent.com/32779449/68996624-fb2a5f80-089c-11ea-8dc2-386e4f11b69a.png)

All the best! This is cool plugin!

**Comment by PikaMug** [comment]
Sorry that I'm just getting to this. In your situation, when using commands to handle the GPS plugin, it is not necessary to use the GPS-Quests plugin, as you're essentially competing with it.
