### ISSUE TITLE
Wrong targeting 

### ISSUE THREAD

**Issue by enterih** [PikaMug/GPS-Quests#4]
Hey, i just tested quest, where a player have go to NPC with the ID 47 but GPS will target the NPC with ID 29. I redefined the NPC but the issue still exist.

After more test this issue happens on every steps in this one quest. As i removed the NPC 29 then the GPS start to follow NPC 30. A Serverrestart won't help

Using Spigot 1.15.2
Quests 3.9.4
GPS 2.19
GPSQuests 1.2

No Error/warn in log

**Comment by PikaMug** [comment]
Thanks for the report. Please provide the quest you're using to test with from the _quests.yml_ file, using a site like Pastebin/Hastebin.

**Comment by enterih** [comment]
https://pastebin.com/RP8z4ckT

Hope you can reproduce it

**Comment by PikaMug** [comment]
Should be resolved with the 1.7 release.
