### ISSUE TITLE
Problem with GPS-Quests 1.6 spam message

### ISSUE THREAD

**Issue by legendofgow** [PikaMug/GPS-Quests#8]
![obraz_2022-04-18_182625231](https://user-images.githubusercontent.com/88216155/163839580-1dd66c32-1a0a-4b1f-a1c6-faf8698c195c.png)

Hello, I have problem with GPS-Quests 1.6 :)  after taking the quest, the plugin will spam the chat with messages, e.g. "GPS Started" all the time,  after uninstalling the gps quest plugin, it returns to normal, is someone currently using it and knows where the problem may be? I have all the plugins on the newest versions :) and funny is that when you are OP spam disappears and the plugin is working properly :D So why is it working properly on OP and not for ordinary users :D

Paper 1.18.2

**Comment by PikaMug** [comment]
Thanks for the report. I wasn't able to replicate this. Please share the associated quest from your _quests.yml_ file using a service like Pastebin.

**Comment by legendofgow** [comment]
Most of the time I can solve such problems myself, but now it's hard for me to find suspects :)
The most strange is the situation with the OP

Here is an exemplary quest to reach the location and kill 5 wolves, but this error is on most quests
https://pastebin.com/RpMPf8G1

Or here easy quest to craft cake and talk to npc 

https://pastebin.com/13upwrLn

You take a quest, the gps shows up and starts refreshing itself every second spamming chat,
when I give myself OP the problem completely disappears and everything is normal :) 
there are no console errors

I can record it if I need to :)
if the problem disappears after giving yourself OP, there may be some kind of permission issue?

**Comment by legendofgow** [comment]
I found the cause of the problem, this is the plugin:

https://www.spigotmc.org/resources/questsbar.100634/

behavior returns to normal after removal
can you confirm it with this plugin?

**Comment by PikaMug** [comment]
This doesn't happen on the Lectern SMP or my local server. What is your GPS version?

**Comment by PikaMug** [comment]
I was unable to replicate this using your example quest, on the Lectern server or locally, with or without QuestsBar installed. I was, however, able to get the message to appear up to 3 times in a row due to an oversight in GPS-Quests (again, regardless of whether QuestsBar was installed). That has been resolved with today's release.

I'll keep this open pending further investigation.
